platform :ios, "8.0"
use_frameworks!

target 'PayCode' do
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'CardIO'
pod 'FontAwesomeKit'
pod 'TGLStackedViewController'

end

target 'PayCodeTests' do

end

target 'PayCodeUITests' do

end

