platform :ios, "8.0"
use_frameworks!

target 'PayCode' do
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'PayPal-iOS-SDK'
pod 'FontAwesomeKit'
pod 'TGLStackedViewController'
pod 'OneSignal' 

end

target 'PayCodeTests' do

end

target 'PayCodeUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
        end
    end
end

